service: vector-db

frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./
  environment:
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    CLOUDINARY_API_SECRET: ${env:CLOUDINARY_API_SECRET}
    OPENAI_KEY: ${env:OPENAI_KEY}
    ELEVENLABS_API_KEY: ${env:ELEVENLABS_API_KEY}
    SERVER_ID: ${env:SERVER_ID}
    CHANNEL_ID: ${env:CHANNEL_ID}
    SALAI_TOKEN: ${env:SALAI_TOKEN}
    GREEN_API_TOKEN: ${env:GREEN_API_TOKEN}
    POSTGRES_URL: ${env:POSTGRES_URL}
    POSTGRES_URL_NON_POOLING: ${env:POSTGRES_URL_NON_POOLING}
    POSTGRES_PRISMA_URL: ${env:POSTGRES_PRISMA_URL}
    POSTGRES_USER: ${env:POSTGRES_USER}
    POSTGRES_HOST: ${env:POSTGRES_HOST}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
    POSTGRES_DATABASE: ${env:POSTGRES_DATABASE}
    PINECONE_API_KEY: ${env:PINECONE_API_KEY}
    PINECONE_ENVIRONMENT: ${env:PINECONE_ENVIRONMENT}
    PINECONE_INDEX: ${env:PINECONE_INDEX}
    HUGGINGFACE_TOKEN: ${env:HUGGINGFACE_TOKEN}

functions:
  hello:
    image:
      name: appimage
