service: vector-db

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./
  environment:
    OPENAI_KEY: ${env:OPENAI_KEY}
    POSTGRES_URL: ${env:POSTGRES_URL}
    PINECONE_API_KEY: ${env:PINECONE_API_KEY}
    PINECONE_ENVIRONMENT: ${env:PINECONE_ENVIRONMENT}
    PINECONE_INDEX: ${env:PINECONE_INDEX}

functions:
  hello:
    image:
      name: appimage
